[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
gloo-net = "0.5"
serde = { version = "1", features = ["derive"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
chrono = { version = "0.4", features = ["serde"] }
